obstacle_range: 5.5
raytrace_range: 6.0
#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
#robot_radius: ir_of_robot
robot_radius: 0.15 # distance a circular robot should be clear of the obstacle
#inflation_radius: 3.0
transform_tolerance: 0.5
update_frequency: 4.0
publish_frequency: 3.0
robot_base_frame: base_link


static:
  map_topic:/map
  subscribe_to_updates:true

obstacles_laser:
  enabled: true
  observation_sources: laser_scan_sensor #point_cloud_sensor
  laser_scan_sensor: {sensor_frame: RP_Link, data_type: LaserScan, topic: scan, marking: true, clearing: true}

inflation_g:
  enabled: true
  inflation_radius: 0.06
    
inflation_l:
  enabled: true
  inflation_radius: 0.03
