# static_map - True if using existing map

global_costmap:
  global_frame: map
 

  resolution: 0.05
  rolling_window: false
  track_unknown_space: true
 # static_map: true
  #width: 10.0
  #height: 10.0
  plugins:
    - {name: static,                  type: "costmap_2d::StaticLayer"}
    - {name: obstacles_laser,         type: "costmap_2d::VoxelLayer"}
    - {name: inflation_g,               type: "costmap_2d::InflationLayer"}
