local_costmap:
  global_frame: odom


  #static_map: false
  rolling_window: true
  width: 1.5
  height: 1.5
  resolution: 0.05
  plugins:
    - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_l,                 type: "costmap_2d::InflationLayer"}